#!/usr/bin/env python

"""Analyze Songling CAN sniff CSV logs.

This helper reads the CSV files generated by `sniff_can_frames.py` and prints:
- per-interface arbitration ID summaries
- candidate IDs whose payload activity increases from an idle capture to a motion capture

Examples:
    python examples/songling_aloha/analyze_can_sniff.py \
      --capture-dir /tmp/songling_can_sniff

    python examples/songling_aloha/analyze_can_sniff.py \
      --idle-dir /tmp/songling_can_idle \
      --active-dir /tmp/songling_can_move
"""

from __future__ import annotations

import argparse
import csv
from dataclasses import dataclass, field
from pathlib import Path

try:
    from songling_protocol import SONGLING_STATE_SPECS
except ModuleNotFoundError:
    from examples.songling_aloha.songling_protocol import SONGLING_STATE_SPECS


@dataclass
class IDStats:
    arbitration_id: str
    count: int = 0
    first_ts: float | None = None
    last_ts: float | None = None
    unique_payloads: set[str] = field(default_factory=set)
    changed_payload_count: int = 0
    last_payload: str | None = None
    dlcs: set[int] = field(default_factory=set)
    sample_payloads: list[str] = field(default_factory=list)

    def add(self, timestamp: float, dlc: int, data_hex: str) -> None:
        self.count += 1
        if self.first_ts is None:
            self.first_ts = timestamp
        self.last_ts = timestamp
        self.dlcs.add(dlc)
        self.unique_payloads.add(data_hex)
        if self.last_payload is not None and self.last_payload != data_hex:
            self.changed_payload_count += 1
        self.last_payload = data_hex
        if data_hex not in self.sample_payloads and len(self.sample_payloads) < 3:
            self.sample_payloads.append(data_hex)

    @property
    def duration_s(self) -> float:
        if self.first_ts is None or self.last_ts is None:
            return 0.0
        return max(self.last_ts - self.first_ts, 0.0)

    @property
    def rate_hz(self) -> float:
        if self.duration_s <= 0.0:
            return float(self.count)
        return float(self.count) / self.duration_s

    @property
    def unique_payload_count(self) -> int:
        return len(self.unique_payloads)

    @property
    def change_ratio(self) -> float:
        if self.count <= 1:
            return 0.0
        return float(self.changed_payload_count) / float(self.count - 1)


def _load_payloads(csv_path: Path, arbitration_id: str) -> list[bytes]:
    target = arbitration_id.strip().upper()
    payloads: list[bytes] = []
    with csv_path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            if str(row["arbitration_id"]).strip().upper() != target:
                continue
            payloads.append(bytes.fromhex(str(row["data_hex"]).strip()))
    return payloads


def _load_csv_stats(csv_path: Path) -> dict[str, IDStats]:
    stats: dict[str, IDStats] = {}
    with csv_path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        required = {"timestamp", "arbitration_id", "dlc", "data_hex"}
        if not required.issubset(set(reader.fieldnames or [])):
            raise ValueError(f"{csv_path} is missing required columns: {sorted(required)}")

        for row in reader:
            arbitration_id = str(row["arbitration_id"]).strip().upper()
            timestamp = float(row["timestamp"])
            dlc = int(row["dlc"])
            data_hex = str(row["data_hex"]).strip().upper()

            item = stats.get(arbitration_id)
            if item is None:
                item = IDStats(arbitration_id=arbitration_id)
                stats[arbitration_id] = item
            item.add(timestamp=timestamp, dlc=dlc, data_hex=data_hex)
    return stats


def _resolve_csvs(directory: Path) -> list[Path]:
    csvs = sorted(p for p in directory.glob("*.csv") if p.is_file())
    if not csvs:
        raise FileNotFoundError(f"No CSV files found in {directory}")
    return csvs


def _format_stats_line(stats: IDStats) -> str:
    payload_preview = ", ".join(stats.sample_payloads) if stats.sample_payloads else "-"
    dlc_text = ",".join(str(v) for v in sorted(stats.dlcs)) if stats.dlcs else "-"
    return (
        f"{stats.arbitration_id:>8}  "
        f"count={stats.count:>6}  "
        f"rate={stats.rate_hz:>8.1f} Hz  "
        f"unique={stats.unique_payload_count:>4}  "
        f"change_ratio={stats.change_ratio:>6.2f}  "
        f"dlc={dlc_text:<5}  "
        f"samples={payload_preview}"
    )


def _print_summary(csv_path: Path, stats: dict[str, IDStats], top: int) -> None:
    print(f"\n=== Summary: {csv_path} ===")
    print(f"IDs observed: {len(stats)}")
    ranked = sorted(
        stats.values(),
        key=lambda item: (item.unique_payload_count, item.change_ratio, item.count),
        reverse=True,
    )
    for item in ranked[:top]:
        print(_format_stats_line(item))


@dataclass
class DiffRow:
    arbitration_id: str
    idle: IDStats | None
    active: IDStats | None

    @property
    def activity_gain(self) -> float:
        idle_score = 0.0 if self.idle is None else (self.idle.unique_payload_count + self.idle.change_ratio * 10.0)
        active_score = (
            0.0 if self.active is None else (self.active.unique_payload_count + self.active.change_ratio * 10.0)
        )
        return active_score - idle_score


def _print_diff(idle_path: Path, active_path: Path, idle_stats: dict[str, IDStats], active_stats: dict[str, IDStats], top: int) -> None:
    print(f"\n=== Diff: idle={idle_path.name} vs active={active_path.name} ===")
    all_ids = sorted(set(idle_stats) | set(active_stats))
    rows = [DiffRow(arbitration_id=arb_id, idle=idle_stats.get(arb_id), active=active_stats.get(arb_id)) for arb_id in all_ids]
    rows.sort(
        key=lambda row: (
            row.activity_gain,
            0.0 if row.active is None else row.active.rate_hz,
            0 if row.active is None else row.active.unique_payload_count,
        ),
        reverse=True,
    )

    for row in rows[:top]:
        idle = row.idle
        active = row.active
        idle_text = (
            f"idle(rate={idle.rate_hz:.1f}, unique={idle.unique_payload_count}, change={idle.change_ratio:.2f})"
            if idle is not None
            else "idle(missing)"
        )
        active_text = (
            "active("
            f"rate={active.rate_hz:.1f}, unique={active.unique_payload_count}, change={active.change_ratio:.2f}, "
            f"samples={', '.join(active.sample_payloads) if active.sample_payloads else '-'}"
            ")"
            if active is not None
            else "active(missing)"
        )
        print(f"{row.arbitration_id:>8}  gain={row.activity_gain:>7.2f}  {idle_text}  {active_text}")


def _field_stats(values: list[int]) -> str:
    if not values:
        return "n=0"
    return f"min={min(values)} max={max(values)} unique={len(set(values))}"


def _print_payload_detail(csv_path: Path, arbitration_id: str) -> None:
    payloads = _load_payloads(csv_path, arbitration_id)
    if not payloads:
        print(f"\n=== Detail: {csv_path.name} {arbitration_id.upper()} ===")
        print("No payloads found.")
        return

    byte_uniques = []
    for idx in range(8):
        vals = [payload[idx] for payload in payloads if len(payload) > idx]
        byte_uniques.append((idx, len(set(vals)), min(vals), max(vals)))

    be16_0 = [int.from_bytes(payload[0:2], byteorder="big", signed=True) for payload in payloads if len(payload) >= 2]
    be16_1 = [int.from_bytes(payload[2:4], byteorder="big", signed=True) for payload in payloads if len(payload) >= 4]
    le16_0 = [int.from_bytes(payload[0:2], byteorder="little", signed=True) for payload in payloads if len(payload) >= 2]
    le16_1 = [int.from_bytes(payload[2:4], byteorder="little", signed=True) for payload in payloads if len(payload) >= 4]
    be32 = [int.from_bytes(payload[0:4], byteorder="big", signed=True) for payload in payloads if len(payload) >= 4]
    le32 = [int.from_bytes(payload[0:4], byteorder="little", signed=True) for payload in payloads if len(payload) >= 4]

    samples = []
    for payload in payloads:
        hex_payload = payload.hex().upper()
        if hex_payload not in samples:
            samples.append(hex_payload)
        if len(samples) >= 5:
            break

    print(f"\n=== Detail: {csv_path.name} {arbitration_id.upper()} ===")
    print(f"frames={len(payloads)} unique_payloads={len(set(payloads))}")
    print("samples=" + ", ".join(samples))
    print("bytes=" + "; ".join(f"b{idx}:unique={unique},range=[{vmin},{vmax}]" for idx, unique, vmin, vmax in byte_uniques))
    print(f"be16[0:2]: {_field_stats(be16_0)}")
    print(f"be16[2:4]: {_field_stats(be16_1)}")
    print(f"le16[0:2]: {_field_stats(le16_0)}")
    print(f"le16[2:4]: {_field_stats(le16_1)}")
    print(f"be32[0:4]: {_field_stats(be32)}")
    print(f"le32[0:4]: {_field_stats(le32)}")


def _analyze_capture_dir(capture_dir: Path, top: int) -> None:
    for csv_path in _resolve_csvs(capture_dir):
        stats = _load_csv_stats(csv_path)
        _print_summary(csv_path, stats, top=top)


def _analyze_idle_vs_active(idle_dir: Path, active_dir: Path, top: int) -> None:
    idle_csvs = {path.name: path for path in _resolve_csvs(idle_dir)}
    active_csvs = {path.name: path for path in _resolve_csvs(active_dir)}
    common = sorted(set(idle_csvs) & set(active_csvs))
    if not common:
        raise FileNotFoundError(
            f"No matching CSV filenames found between {idle_dir} and {active_dir}. "
            "Expected names like can0.csv/can1.csv in both directories."
        )

    for name in common:
        idle_path = idle_csvs[name]
        active_path = active_csvs[name]
        idle_stats = _load_csv_stats(idle_path)
        active_stats = _load_csv_stats(active_path)
        _print_summary(idle_path, idle_stats, top=top)
        _print_summary(active_path, active_stats, top=top)
        _print_diff(idle_path, active_path, idle_stats, active_stats, top=top)


def main() -> None:
    parser = argparse.ArgumentParser(description="Analyze Songling CAN sniff CSV logs.")
    parser.add_argument("--capture-dir", type=Path, default=None, help="Analyze one capture directory.")
    parser.add_argument("--idle-dir", type=Path, default=None, help="Idle capture directory for diff analysis.")
    parser.add_argument("--active-dir", type=Path, default=None, help="Active/motion capture directory for diff analysis.")
    parser.add_argument("--top", type=int, default=20, help="Number of IDs to print per summary.")
    parser.add_argument(
        "--detail-ids",
        default=None,
        help="Comma-separated arbitration IDs (e.g. 0x251,0x252,0x2A8) for payload field inspection.",
    )
    parser.add_argument(
        "--show-songling-map",
        action="store_true",
        help="Print the current heuristic Songling RX field mapping and exit if no other analysis args are given.",
    )
    args = parser.parse_args()

    if args.show_songling_map:
        print("Current heuristic Songling RX mapping:")
        for arbitration_id, spec in sorted(SONGLING_STATE_SPECS.items()):
            print(
                f"  {hex(arbitration_id)} -> bytes[{spec.byte_offset}:{spec.byte_offset + spec.byte_length}] "
                f"{spec.byteorder} signed={spec.signed} scale={spec.scale} bias={spec.bias}"
            )
        if args.capture_dir is None and args.idle_dir is None and args.active_dir is None:
            return

    if args.capture_dir is not None and (args.idle_dir is not None or args.active_dir is not None):
        raise ValueError("Use either --capture-dir or --idle-dir/--active-dir, not both.")

    if args.capture_dir is not None:
        _analyze_capture_dir(args.capture_dir, top=args.top)
        if args.detail_ids:
            detail_ids = [item.strip().upper() for item in args.detail_ids.split(",") if item.strip()]
            for csv_path in _resolve_csvs(args.capture_dir):
                for arbitration_id in detail_ids:
                    _print_payload_detail(csv_path, arbitration_id)
        return

    if args.idle_dir is None or args.active_dir is None:
        raise ValueError("Provide either --capture-dir or both --idle-dir and --active-dir.")

    _analyze_idle_vs_active(args.idle_dir, args.active_dir, top=args.top)
    if args.detail_ids:
        detail_ids = [item.strip().upper() for item in args.detail_ids.split(",") if item.strip()]
        for directory in (args.idle_dir, args.active_dir):
            for csv_path in _resolve_csvs(directory):
                for arbitration_id in detail_ids:
                    _print_payload_detail(csv_path, arbitration_id)


if __name__ == "__main__":
    main()
